# Generated by Django 3.2.5 on 2022-06-27 07:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Klasa',
                'verbose_name_plural': 'Klasa',
            },
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(choices=[(0, 0), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=2, unique=True)),
                ('punkty', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Oceny',
                'verbose_name_plural': 'Oceny',
            },
        ),
        migrations.CreateModel(
            name='Oryginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Dokumenty',
                'verbose_name_plural': 'Dokumenty',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(default='', max_length=100, verbose_name='Nazwisko')),
                ('second_name1', models.CharField(default='', max_length=100, verbose_name='Pierwsze imię')),
                ('second_name2', models.CharField(blank=True, max_length=100, verbose_name='Drugie imię')),
                ('pesel', models.CharField(default=0, max_length=12, unique=True, verbose_name='Pesel')),
                ('internat', models.BooleanField(default=False, verbose_name='Internat')),
                ('j_pol_egz', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='J.polski punkty egzamin')),
                ('mat_egz', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='Matematyka punkty egzamin')),
                ('j_obcy_egz', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)], verbose_name='J.obcy punkty egzamin')),
                ('sw_wyr', models.BooleanField(default=False, verbose_name='Świadectwo z wyróżnieniem')),
                ('konk_ponad_wyr', models.IntegerField(choices=[(0, 0), (5, 5), (7, 7), (10, 10)], default=0, verbose_name='Konkurs ponadwojewódzki')),
                ('konk_woj', models.IntegerField(choices=[(0, 0), (3, 3), (5, 5), (7, 7), (10, 10)], default=0, verbose_name='Konkurs wojewódzki')),
                ('konk_przedm', models.IntegerField(choices=[(0, 0), (3, 3), (4, 4), (10, 10)], default=0, verbose_name='Konkurs przedmiotowy')),
                ('konk_inne', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0, verbose_name='Konkursy inne ')),
                ('aktyw_spol', models.IntegerField(choices=[(0, 0), (3, 3)], default=0, verbose_name='Aktywność społeczna')),
                ('suma_pkt', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('biol_oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biol_oc', to='licznik.ocena', verbose_name='Biologia ocena')),
                ('clas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='licznik.klasa', verbose_name='Klasa')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='licznik.oryginal', verbose_name='Dokument')),
                ('inf_oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inf_oc', to='licznik.ocena', verbose_name='Informatyka ocena')),
                ('j_pol_oc', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='j_pol_oc', to='licznik.ocena', to_field='ocena', verbose_name='J.polski ocena')),
                ('mat_oc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mat_oc', to='licznik.ocena', verbose_name='Matematyka ocena')),
            ],
            options={
                'verbose_name': 'Kandydat',
                'verbose_name_plural': 'Kandydat',
            },
        ),
    ]
