# Generated by Django 3.2.5 on 2021-12-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oryginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='')),
            ],
        ),
    ]
