# Generated by Django 3.2.5 on 2022-06-27 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0002_alter_kandydat_j_pol_oc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandydat',
            name='biol_oc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biol_oc', to='licznik.ocena', verbose_name='Biologia ocena'),
        ),
        migrations.AlterField(
            model_name='kandydat',
            name='inf_oc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inf_oc', to='licznik.ocena', verbose_name='Informatyka ocena'),
        ),
        migrations.AlterField(
            model_name='kandydat',
            name='mat_oc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mat_oc', to='licznik.ocena', verbose_name='Matematyka ocena'),
        ),
    ]
