# Generated by Django 3.2.5 on 2021-12-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0002_oryginal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=2, unique=True)),
                ('punkty', models.IntegerField(default=2)),
            ],
        ),
    ]
