# Generated by Django 3.2.5 on 2021-12-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0003_ocena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocena',
            name='nota',
        ),
        migrations.AddField(
            model_name='ocena',
            name='ocena',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=2, unique=True),
        ),
    ]
