# Generated by Django 3.2.5 on 2021-12-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0004_auto_20211228_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocena',
            name='punkty',
            field=models.IntegerField(default=2, editable=False),
        ),
    ]
