# Generated by Django 3.2.5 on 2021-12-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0005_alter_ocena_punkty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocena',
            name='ocena',
            field=models.IntegerField(default=2, unique=True),
        ),
    ]
