# Generated by Django 3.2.5 on 2022-01-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0008_auto_20211228_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kandydat',
            options={'verbose_name': 'Kandydat', 'verbose_name_plural': 'Kandydat'},
        ),
        migrations.AlterModelOptions(
            name='klasa',
            options={'verbose_name': 'Klasa', 'verbose_name_plural': 'Klasa'},
        ),
        migrations.AlterModelOptions(
            name='ocena',
            options={'verbose_name': 'Oceny', 'verbose_name_plural': 'Oceny'},
        ),
        migrations.AlterModelOptions(
            name='oryginal',
            options={'verbose_name': 'Dokumenty', 'verbose_name_plural': 'Dokumenty'},
        ),
        migrations.AlterField(
            model_name='kandydat',
            name='biol_oc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biol_oc', to='licznik.ocena', verbose_name='Biologia ocena'),
        ),
        migrations.AlterField(
            model_name='kandydat',
            name='inf_oc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inf_oc', to='licznik.ocena', verbose_name='Informatyka ocena'),
        ),
        migrations.AlterField(
            model_name='kandydat',
            name='j_pol_oc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='j_pol_oc', to='licznik.ocena', verbose_name='J.polski ocena'),
        ),
        migrations.AlterField(
            model_name='kandydat',
            name='mat_oc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mat_oc', to='licznik.ocena', verbose_name='Matematyka ocena'),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='punkty',
            field=models.IntegerField(default=2),
        ),
    ]
