# Generated by Django 3.2.3 on 2022-01-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0009_auto_20220105_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
