# Generated by Django 3.2.5 on 2022-01-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licznik', '0012_alter_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandydat',
            name='suma_pkt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
